# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1920, 1080)
        MainWindow.setStyleSheet("background-color: #1F1B2C;  /* Темный фон для кнопок */")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.CanvasForLeftButtons = QtWidgets.QFrame(self.centralwidget)
        self.CanvasForLeftButtons.setGeometry(QtCore.QRect(0, -40, 227, 1121))
        self.CanvasForLeftButtons.setStyleSheet(" background-color: #171F34;  /* Темный фон для кнопок */")
        self.CanvasForLeftButtons.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.CanvasForLeftButtons.setFrameShadow(QtWidgets.QFrame.Raised)
        self.CanvasForLeftButtons.setObjectName("CanvasForLeftButtons")
        self.main_button = QtWidgets.QPushButton(self.CanvasForLeftButtons)
        self.main_button.setGeometry(QtCore.QRect(0, 130, 231, 41))
        self.main_button.setStyleSheet("QPushButton {\n"
"    background-color: #171F34;  /* Темный фон для кнопок */\n"
"    color: #FFFFFF;  /* Белый текст */\n"
"    border: none;  /* Убрать рамки */\n"
"    border-radius: 5px;  /* Скругленные углы */\n"
"    text-align: left;\n"
"    padding-left: 25px; /* Отступ слева для текста */\n"
"    font-size: 16px;  /* Размер шрифта */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #3B3F45;  /* Более светлый фон при наведении */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgba(255, 255, 255, 0.1);  /* 10% белый фон при нажатии */\n"
"    border: 2px solid #FFFFFF;  /* Белая рамка при нажатии */\n"
"}\n"
"")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Images/Group 15.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.main_button.setIcon(icon)
        self.main_button.setIconSize(QtCore.QSize(20, 20))
        self.main_button.setObjectName("main_button")
        self.equipment_button = QtWidgets.QPushButton(self.CanvasForLeftButtons)
        self.equipment_button.setGeometry(QtCore.QRect(0, 185, 231, 41))
        self.equipment_button.setStyleSheet("QPushButton {\n"
"    background-color: #171F34;  /* Темный фон для кнопок */\n"
"    color: #FFFFFF;  /* Белый текст */\n"
"    border: none;  /* Убрать рамки */\n"
"    border-radius: 5px;  /* Скругленные углы */\n"
"   text-align: left;\n"
"    padding-left: 25px; /* Отступ слева для текста */\n"
"    font-size: 16px;  /* Размер шрифта */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #3B3F45;  /* Более светлый фон при наведении */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgba(255, 255, 255, 0.1);  /* 10% белый фон при нажатии */\n"
"    border: 2px solid #FFFFFF;  /* Белая рамка при нажатии */\n"
"}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("Images/Group 14.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.equipment_button.setIcon(icon1)
        self.equipment_button.setIconSize(QtCore.QSize(20, 20))
        self.equipment_button.setObjectName("equipment_button")
        self.pacient_button = QtWidgets.QPushButton(self.CanvasForLeftButtons)
        self.pacient_button.setGeometry(QtCore.QRect(0, 235, 231, 41))
        self.pacient_button.setStyleSheet("QPushButton {\n"
"    image: url(:/Profile/C:/Users/Abraham/Desktop/321.png);\n"
"    background-color: #171F34;  /* Темный фон для кнопок */\n"
"    color: #FFFFFF;  /* Белый текст */\n"
"    border: none;  /* Убрать рамки */\n"
"    border-radius: 5px;  /* Скругленные углы */\n"
"   text-align: left;\n"
"    padding-left: 25px; /* Отступ слева для текста */\n"
"    font-size: 16px;  /* Размер шрифта */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #3B3F45;  /* Более светлый фон при наведении */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgba(255, 255, 255, 0.1);  /* 10% белый фон при нажатии */\n"
"    border: 2px solid #FFFFFF;  /* Белая рамка при нажатии */\n"
"}")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("Images/Group 10.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pacient_button.setIcon(icon2)
        self.pacient_button.setIconSize(QtCore.QSize(20, 20))
        self.pacient_button.setObjectName("pacient_button")
        self.documents_button = QtWidgets.QPushButton(self.CanvasForLeftButtons)
        self.documents_button.setGeometry(QtCore.QRect(0, 285, 231, 41))
        self.documents_button.setStyleSheet("QPushButton {\n"
"    background-color: #171F34;  /* Темный фон для кнопок */\n"
"    color: #FFFFFF;  /* Белый текст */\n"
"    border: none;  /* Убрать рамки */\n"
"    border-radius: 5px;  /* Скругленные углы */\n"
"    text-align: left;\n"
"    padding-left: 25px; /* Отступ слева для текста */\n"
"    font-size: 16px;  /* Размер шрифта */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #3B3F45;  /* Более светлый фон при наведении */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgba(255, 255, 255, 0.1);  /* 10% белый фон при нажатии */\n"
"    border: 2px solid #FFFFFF;  /* Белая рамка при нажатии */\n"
"}")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("Images/Group 13.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.documents_button.setIcon(icon3)
        self.documents_button.setIconSize(QtCore.QSize(20, 20))
        self.documents_button.setObjectName("documents_button")
        self.chat_button = QtWidgets.QPushButton(self.CanvasForLeftButtons)
        self.chat_button.setGeometry(QtCore.QRect(0, 335, 231, 41))
        self.chat_button.setStyleSheet("QPushButton {\n"
"    background-color: #171F34;  /* Темный фон для кнопок */\n"
"    color: #FFFFFF;  /* Белый текст */\n"
"    border: none;  /* Убрать рамки */\n"
"    border-radius: 5px;  /* Скругленные углы */\n"
"    text-align: left;\n"
"    padding-left: 25px; /* Отступ слева для текста */\n"
"    font-size: 16px;  /* Размер шрифта */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #3B3F45;  /* Более светлый фон при наведении */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgba(255, 255, 255, 0.1);  /* 10% белый фон при нажатии */\n"
"    border: 2px solid #FFFFFF;  /* Белая рамка при нажатии */\n"
"}")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("Images/Group 12.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.chat_button.setIcon(icon4)
        self.chat_button.setIconSize(QtCore.QSize(20, 20))
        self.chat_button.setObjectName("chat_button")
        self.settings_button = QtWidgets.QPushButton(self.CanvasForLeftButtons)
        self.settings_button.setGeometry(QtCore.QRect(0, 435, 231, 41))
        self.settings_button.setStyleSheet("QPushButton {\n"
"    background-color: #171F34;  /* Темный фон для кнопок */\n"
"    color: #FFFFFF;  /* Белый текст */\n"
"    border: none;  /* Убрать рамки */\n"
"    border-radius: 5px;  /* Скругленные углы */\n"
"    text-align: left;\n"
"    padding-left: 25px; /* Отступ слева для текста */\n"
"    font-size: 16px;  /* Размер шрифта */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #3B3F45;  /* Более светлый фон при наведении */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgba(255, 255, 255, 0.1);  /* 10% белый фон при нажатии */\n"
"    border: 2px solid #FFFFFF;  /* Белая рамка при нажатии */\n"
"}")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("Images/Group 11.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.settings_button.setIcon(icon5)
        self.settings_button.setIconSize(QtCore.QSize(20, 20))
        self.settings_button.setObjectName("settings_button")
        self.exit_button = QtWidgets.QPushButton(self.CanvasForLeftButtons)
        self.exit_button.setGeometry(QtCore.QRect(0, 970, 231, 41))
        self.exit_button.setStyleSheet("QPushButton {\n"
"    background-color: #171F34;  /* Темный фон для кнопок */\n"
"    color: #FFFFFF;  /* Белый текст */\n"
"    border: none;  /* Убрать рамки */\n"
"    border-radius: 5px;  /* Скругленные углы */\n"
"   text-align: left;\n"
"    padding-left: 25px; /* Отступ слева для текста */\n"
"    font-size: 16px;  /* Размер шрифта */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #3B3F45;  /* Более светлый фон при наведении */\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgba(255, 255, 255, 0.1);  /* 10% белый фон при нажатии */\n"
"    border: 2px solid #FFFFFF;  /* Белая рамка при нажатии */\n"
"}")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("Images/Group 16.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.exit_button.setIcon(icon6)
        self.exit_button.setIconSize(QtCore.QSize(20, 20))
        self.exit_button.setObjectName("exit_button")
        self.directory_button = QtWidgets.QPushButton(self.CanvasForLeftButtons)
        self.directory_button.setGeometry(QtCore.QRect(0, 385, 231, 41))
        self.directory_button.setStyleSheet("QPushButton {\n"
"    background-color: #171F34;  /* Темный фон для кнопок */\n"
"    color: #FFFFFF;  /* Белый текст */\n"
"    border: none;  /* Убрать рамки */\n"
"    border-radius: 5px;  /* Скругленные углы */\n"
"    text-align: left;\n"
"    padding-left: 25px; /* Отступ слева для текста */\n"
"    font-size: 16px;  /* Размер шрифта */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #3B3F45;  /* Более светлый фон при наведении */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgba(255, 255, 255, 0.1);  /* 10% белый фон при нажатии */\n"
"    border: 2px solid #FFFFFF;  /* Белая рамка при нажатии */\n"
"}")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("Images/lists.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.directory_button.setIcon(icon7)
        self.directory_button.setIconSize(QtCore.QSize(20, 20))
        self.directory_button.setObjectName("directory_button")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(290, 0, 1681, 1061))
        self.stackedWidget.setObjectName("stackedWidget")
        self.HomePage = QtWidgets.QWidget()
        self.HomePage.setObjectName("HomePage")
        self.label_9 = QtWidgets.QLabel(self.HomePage)
        self.label_9.setGeometry(QtCore.QRect(350, 330, 891, 151))
        self.label_9.setStyleSheet(" color: #FFFFFF;  /* Белый текст */\n"
"    border: none;  /* Убрать рамки */\n"
"    font-size: 100px;  /* Размер шрифта */")
        self.label_9.setObjectName("label_9")
        self.stackedWidget.addWidget(self.HomePage)
        self.MainPage = QtWidgets.QWidget()
        self.MainPage.setEnabled(True)
        self.MainPage.setObjectName("MainPage")
        self.label = QtWidgets.QLabel(self.MainPage)
        self.label.setGeometry(QtCore.QRect(20, 70, 71, 21))
        self.label.setStyleSheet("color: rgb(255, 255, 255);\n"
"font-size: 14px;  /* Размер шрифта */\n"
"border: none;  /* Убрать рамки */")
        self.label.setObjectName("label")
        self.frame = QtWidgets.QFrame(self.MainPage)
        self.frame.setGeometry(QtCore.QRect(20, 110, 421, 62))
        self.frame.setStyleSheet("QFrame {\n"
"    border: 1px solid gray;  /* Ширина и цвет границы */\n"
"    background-color: #171F34;  /* Темный фон для кнопок */\n"
"    border-radius: 5px;  /* Скругленные углы */         \n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setGeometry(QtCore.QRect(300, 20, 111, 23))
        self.pushButton.setStyleSheet("QPushButton {\n"
"    background-color: #171F34;  /* Темный фон для кнопок */\n"
"    color: #4277FF;  /* Белый текст */\n"
"    border: none;  /* Убрать рамки */\n"
"    border-radius: 5px;  /* Скругленные углы */\n"
"    text-align: left;\n"
"    padding-left: 25px; /* Отступ слева для текста */\n"
"    font-size: 14px;  /* Размер шрифта */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #3B3F45;  /* Более светлый фон при наведении */\n"
"}\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.frame_2 = QtWidgets.QFrame(self.MainPage)
        self.frame_2.setGeometry(QtCore.QRect(20, 190, 421, 352))
        self.frame_2.setStyleSheet("QFrame {\n"
"    border: 1px solid gray;  /* Ширина и цвет границы */\n"
"    background-color: #171F34;  /* Темный фон для кнопок */\n"
"    border-radius: 5px;  /* Скругленные углы */         \n"
"}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        self.label_2.setGeometry(QtCore.QRect(20, 20, 141, 21))
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);\n"
"font-size: 14px;  /* Размер шрифта */\n"
"    border: none;  /* Убрать рамки */")
        self.label_2.setObjectName("label_2")
        self.frame_3 = QtWidgets.QFrame(self.MainPage)
        self.frame_3.setGeometry(QtCore.QRect(470, 110, 721, 434))
        self.frame_3.setStyleSheet("QFrame {\n"
"    border: 1px solid gray;  /* Ширина и цвет границы */\n"
"    background-color: #171F34;  /* Темный фон для кнопок */\n"
"    border-radius: 5px;  /* Скругленные углы */         \n"
"}")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.label_3 = QtWidgets.QLabel(self.MainPage)
        self.label_3.setGeometry(QtCore.QRect(470, 70, 151, 21))
        self.label_3.setStyleSheet("color: rgb(255, 255, 255);\n"
"font-size: 14px;  /* Размер шрифта */\n"
"border: none;  /* Убрать рамки */")
        self.label_3.setObjectName("label_3")
        self.stackedWidget.addWidget(self.MainPage)
        self.EquipmentPage = QtWidgets.QWidget()
        self.EquipmentPage.setObjectName("EquipmentPage")
        self.label_4 = QtWidgets.QLabel(self.EquipmentPage)
        self.label_4.setGeometry(QtCore.QRect(350, 210, 461, 41))
        self.label_4.setStyleSheet(" color: #FFFFFF;  /* Белый текст */\n"
"    border: none;  /* Убрать рамки */\n"
"    font-size: 40px;  /* Размер шрифта */")
        self.label_4.setObjectName("label_4")
        self.stackedWidget.addWidget(self.EquipmentPage)
        self.PacientPage = QtWidgets.QWidget()
        self.PacientPage.setObjectName("PacientPage")
        self.label_5 = QtWidgets.QLabel(self.PacientPage)
        self.label_5.setGeometry(QtCore.QRect(440, 240, 381, 41))
        self.label_5.setStyleSheet(" color: #FFFFFF;  /* Белый текст */\n"
"    border: none;  /* Убрать рамки */\n"
"    font-size: 40px;  /* Размер шрифта */")
        self.label_5.setObjectName("label_5")
        self.stackedWidget.addWidget(self.PacientPage)
        self.DocumentsPage = QtWidgets.QWidget()
        self.DocumentsPage.setObjectName("DocumentsPage")
        self.label_6 = QtWidgets.QLabel(self.DocumentsPage)
        self.label_6.setGeometry(QtCore.QRect(440, 270, 401, 51))
        self.label_6.setStyleSheet(" color: #FFFFFF;  /* Белый текст */\n"
"    border: none;  /* Убрать рамки */\n"
"    font-size: 40px;  /* Размер шрифта */")
        self.label_6.setObjectName("label_6")
        self.stackedWidget.addWidget(self.DocumentsPage)
        self.ChatPage = QtWidgets.QWidget()
        self.ChatPage.setObjectName("ChatPage")
        self.label_7 = QtWidgets.QLabel(self.ChatPage)
        self.label_7.setGeometry(QtCore.QRect(460, 240, 401, 41))
        self.label_7.setStyleSheet(" color: #FFFFFF;  /* Белый текст */\n"
"    border: none;  /* Убрать рамки */\n"
"    font-size: 40px;  /* Размер шрифта */")
        self.label_7.setObjectName("label_7")
        self.stackedWidget.addWidget(self.ChatPage)
        self.DirectoryPage = QtWidgets.QWidget()
        self.DirectoryPage.setObjectName("DirectoryPage")
        self.tabWidget = QtWidgets.QTabWidget(self.DirectoryPage)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 1571, 1011))
        self.tabWidget.setIconSize(QtCore.QSize(20, 20))
        self.tabWidget.setObjectName("tabWidget")
        self.med_inst = QtWidgets.QWidget()
        self.med_inst.setObjectName("med_inst")
        self.add_button_med = QtWidgets.QPushButton(self.med_inst)
        self.add_button_med.setGeometry(QtCore.QRect(190, 30, 131, 23))
        self.add_button_med.setStyleSheet("QPushButton {\n"
"    background-color: #171F34;  /* Темный фон для кнопок */\n"
"    color: #FFFFFF;  /* Белый текст */\n"
"    border: 2px solid white; /* Белая рамка толщиной 2px */    \n"
"    border-radius: 5px;  /* Скругленные углы */\n"
"   text-align: left;\n"
"    padding-left: 25px; /* Отступ слева для текста */\n"
"    font-size: 16px;  /* Размер шрифта */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #3B3F45;  /* Более светлый фон при наведении */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgba(255, 255, 255, 0.1);  /* 10% белый фон при нажатии */\n"
"    border: 2px solid #FFFFFF;  /* Белая рамка при нажатии */\n"
"}")
        self.add_button_med.setObjectName("add_button_med")
        self.delete_button_med = QtWidgets.QPushButton(self.med_inst)
        self.delete_button_med.setGeometry(QtCore.QRect(340, 30, 131, 23))
        self.delete_button_med.setStyleSheet("QPushButton {\n"
"    background-color: #171F34;  /* Темный фон для кнопок */\n"
"    color: #FFFFFF;  /* Белый текст */\n"
"    border: 2px solid white; /* Белая рамка толщиной 2px */    \n"
"    border-radius: 5px;  /* Скругленные углы */\n"
"   text-align: left;\n"
"    padding-left: 25px; /* Отступ слева для текста */\n"
"    font-size: 16px;  /* Размер шрифта */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #3B3F45;  /* Более светлый фон при наведении */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgba(255, 255, 255, 0.1);  /* 10% белый фон при нажатии */\n"
"    border: 2px solid #FFFFFF;  /* Белая рамка при нажатии */\n"
"}")
        self.delete_button_med.setObjectName("delete_button_med")
        self.change_button_med = QtWidgets.QPushButton(self.med_inst)
        self.change_button_med.setGeometry(QtCore.QRect(490, 30, 131, 23))
        self.change_button_med.setStyleSheet("QPushButton {\n"
"    background-color: #171F34;  /* Темный фон для кнопок */\n"
"    color: #FFFFFF;  /* Белый текст */\n"
"    border: 2px solid white; /* Белая рамка толщиной 2px */    \n"
"    border-radius: 5px;  /* Скругленные углы */\n"
"   text-align: left;\n"
"    padding-left: 25px; /* Отступ слева для текста */\n"
"    font-size: 16px;  /* Размер шрифта */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #3B3F45;  /* Более светлый фон при наведении */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgba(255, 255, 255, 0.1);  /* 10% белый фон при нажатии */\n"
"    border: 2px solid #FFFFFF;  /* Белая рамка при нажатии */\n"
"}")
        self.change_button_med.setObjectName("change_button_med")
        self.check_button_med = QtWidgets.QPushButton(self.med_inst)
        self.check_button_med.setGeometry(QtCore.QRect(40, 30, 131, 23))
        self.check_button_med.setStyleSheet("QPushButton {\n"
"    background-color: #171F34;  /* Темный фон для кнопок */\n"
"    color: #FFFFFF;  /* Белый текст */\n"
"    border: 2px solid white; /* Белая рамка толщиной 2px */    \n"
"    border-radius: 5px;  /* Скругленные углы */\n"
"   text-align: left;\n"
"    padding-left: 25px; /* Отступ слева для текста */\n"
"    font-size: 16px;  /* Размер шрифта */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #3B3F45;  /* Более светлый фон при наведении */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgba(255, 255, 255, 0.1);  /* 10% белый фон при нажатии */\n"
"    border: 2px solid #FFFFFF;  /* Белая рамка при нажатии */\n"
"}")
        self.check_button_med.setObjectName("check_button_med")
        self.stackedWidget_2 = QtWidgets.QStackedWidget(self.med_inst)
        self.stackedWidget_2.setGeometry(QtCore.QRect(10, 70, 1661, 901))
        self.stackedWidget_2.setObjectName("stackedWidget_2")
        self.check_page_med = QtWidgets.QWidget()
        self.check_page_med.setObjectName("check_page_med")
        self.tableView = QtWidgets.QTableView(self.check_page_med)
        self.tableView.setGeometry(QtCore.QRect(0, 50, 1541, 851))
        self.tableView.setStyleSheet("   QTableView {\n"
"    color: white; /* Цвет текста в ячейках */\n"
"    background-color: black; /* Цвет фона таблицы */\n"
"    gridline-color: gray; /* Цвет линий сетки */\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"    background-color: black; /* Цвет фона заголовков */\n"
"    color: white; /* Цвет текста в заголовках */\n"
"    border: 1px solid gray; /* Цвет границы заголовков */\n"
"}")
        self.tableView.setObjectName("tableView")
        self.stackedWidget_2.addWidget(self.check_page_med)
        self.add_page_med = QtWidgets.QWidget()
        self.add_page_med.setObjectName("add_page_med")
        self.formLayoutWidget = QtWidgets.QWidget(self.add_page_med)
        self.formLayoutWidget.setGeometry(QtCore.QRect(30, 30, 721, 411))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label_11 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_11.setStyleSheet("background-color: #171F34;  /* Темный фон для кнопок */\n"
"    color: #FFFFFF;  /* Белый текст */\n"
"    border: none;  /* Убрать рамки */\n"
"    border-radius: 5px;  /* Скругленные углы */\n"
"   text-align: left;\n"
"    padding-left: 25px; /* Отступ слева для текста */\n"
"    font-size: 16px;  /* Размер шрифта */")
        self.label_11.setObjectName("label_11")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.label_11)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineEdit_2.setStyleSheet("    color: #FFFFFF;  /* Белый текст */")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.SpanningRole, self.lineEdit_2)
        self.label_12 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_12.setStyleSheet("background-color: #171F34;  /* Темный фон для кнопок */\n"
"    color: #FFFFFF;  /* Белый текст */\n"
"    border: none;  /* Убрать рамки */\n"
"    border-radius: 5px;  /* Скругленные углы */\n"
"   text-align: left;\n"
"    padding-left: 25px; /* Отступ слева для текста */\n"
"    font-size: 16px;  /* Размер шрифта */")
        self.label_12.setObjectName("label_12")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.SpanningRole, self.label_12)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineEdit_3.setStyleSheet("    color: #FFFFFF;  /* Белый текст */")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.SpanningRole, self.lineEdit_3)
        self.label_13 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_13.setStyleSheet("background-color: #171F34;  /* Темный фон для кнопок */\n"
"    color: #FFFFFF;  /* Белый текст */\n"
"    border: none;  /* Убрать рамки */\n"
"    border-radius: 5px;  /* Скругленные углы */\n"
"   text-align: left;\n"
"    padding-left: 25px; /* Отступ слева для текста */\n"
"    font-size: 16px;  /* Размер шрифта */")
        self.label_13.setObjectName("label_13")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.SpanningRole, self.label_13)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineEdit_4.setStyleSheet("    color: #FFFFFF;  /* Белый текст */")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.SpanningRole, self.lineEdit_4)
        self.label_14 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_14.setStyleSheet("background-color: #171F34;  /* Темный фон для кнопок */\n"
"    color: #FFFFFF;  /* Белый текст */\n"
"    border: none;  /* Убрать рамки */\n"
"    border-radius: 5px;  /* Скругленные углы */\n"
"   text-align: left;\n"
"    padding-left: 25px; /* Отступ слева для текста */\n"
"    font-size: 16px;  /* Размер шрифта */")
        self.label_14.setObjectName("label_14")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.SpanningRole, self.label_14)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineEdit_5.setStyleSheet("    color: #FFFFFF;  /* Белый текст */")
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.SpanningRole, self.lineEdit_5)
        self.label_15 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_15.setStyleSheet("background-color: #171F34;  /* Темный фон для кнопок */\n"
"    color: #FFFFFF;  /* Белый текст */\n"
"    border: none;  /* Убрать рамки */\n"
"    border-radius: 5px;  /* Скругленные углы */\n"
"   text-align: left;\n"
"    padding-left: 25px; /* Отступ слева для текста */\n"
"    font-size: 16px;  /* Размер шрифта */")
        self.label_15.setObjectName("label_15")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.SpanningRole, self.label_15)
        self.lineEdit_6 = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineEdit_6.setStyleSheet("    color: #FFFFFF;  /* Белый текст */")
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.SpanningRole, self.lineEdit_6)
        self.label_16 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_16.setStyleSheet("background-color: #171F34;  /* Темный фон для кнопок */\n"
"    color: #FFFFFF;  /* Белый текст */\n"
"    border: none;  /* Убрать рамки */\n"
"    border-radius: 5px;  /* Скругленные углы */\n"
"   text-align: left;\n"
"    padding-left: 25px; /* Отступ слева для текста */\n"
"    font-size: 16px;  /* Размер шрифта */")
        self.label_16.setObjectName("label_16")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.SpanningRole, self.label_16)
        self.lineEdit_7 = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineEdit_7.setStyleSheet("    color: #FFFFFF;  /* Белый текст */")
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.formLayout.setWidget(11, QtWidgets.QFormLayout.SpanningRole, self.lineEdit_7)
        self.label_17 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_17.setStyleSheet("background-color: #171F34;  /* Темный фон для кнопок */\n"
"    color: #FFFFFF;  /* Белый текст */\n"
"    border: none;  /* Убрать рамки */\n"
"    border-radius: 5px;  /* Скругленные углы */\n"
"   text-align: left;\n"
"    padding-left: 25px; /* Отступ слева для текста */\n"
"    font-size: 16px;  /* Размер шрифта */")
        self.label_17.setObjectName("label_17")
        self.formLayout.setWidget(12, QtWidgets.QFormLayout.SpanningRole, self.label_17)
        self.lineEdit_8 = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineEdit_8.setStyleSheet("    color: #FFFFFF;  /* Белый текст */")
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.formLayout.setWidget(13, QtWidgets.QFormLayout.SpanningRole, self.lineEdit_8)
        self.label_18 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_18.setStyleSheet("background-color: #171F34;  /* Темный фон для кнопок */\n"
"    color: #FFFFFF;  /* Белый текст */\n"
"    border: none;  /* Убрать рамки */\n"
"    border-radius: 5px;  /* Скругленные углы */\n"
"   text-align: left;\n"
"    padding-left: 25px; /* Отступ слева для текста */\n"
"    font-size: 16px;  /* Размер шрифта */")
        self.label_18.setObjectName("label_18")
        self.formLayout.setWidget(14, QtWidgets.QFormLayout.SpanningRole, self.label_18)
        self.lineEdit_9 = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineEdit_9.setStyleSheet("    color: #FFFFFF;  /* Белый текст */")
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.formLayout.setWidget(15, QtWidgets.QFormLayout.SpanningRole, self.lineEdit_9)
        self.send_button_med = QtWidgets.QPushButton(self.add_page_med)
        self.send_button_med.setGeometry(QtCore.QRect(290, 460, 131, 23))
        self.send_button_med.setStyleSheet("QPushButton {\n"
"    background-color: #171F34;  /* Темный фон для кнопок */\n"
"    color: #FFFFFF;  /* Белый текст */\n"
"    border: 2px solid white; /* Белая рамка толщиной 2px */    \n"
"    border-radius: 5px;  /* Скругленные углы */\n"
"   text-align: left;\n"
"    padding-left: 25px; /* Отступ слева для текста */\n"
"    font-size: 16px;  /* Размер шрифта */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #3B3F45;  /* Более светлый фон при наведении */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgba(255, 255, 255, 0.1);  /* 10% белый фон при нажатии */\n"
"    border: 2px solid #FFFFFF;  /* Белая рамка при нажатии */\n"
"}")
        self.send_button_med.setObjectName("send_button_med")
        self.stackedWidget_2.addWidget(self.add_page_med)
        self.delete_page_med = QtWidgets.QWidget()
        self.delete_page_med.setObjectName("delete_page_med")
        self.stackedWidget_2.addWidget(self.delete_page_med)
        self.change_page_med = QtWidgets.QWidget()
        self.change_page_med.setObjectName("change_page_med")
        self.stackedWidget_2.addWidget(self.change_page_med)
        self.tabWidget.addTab(self.med_inst, "")
        self.equip = QtWidgets.QWidget()
        self.equip.setObjectName("equip")
        self.delete_button_eq = QtWidgets.QPushButton(self.equip)
        self.delete_button_eq.setGeometry(QtCore.QRect(340, 30, 131, 23))
        self.delete_button_eq.setStyleSheet("QPushButton {\n"
"    background-color: #171F34;  /* Темный фон для кнопок */\n"
"    color: #FFFFFF;  /* Белый текст */\n"
"    border: 2px solid white; /* Белая рамка толщиной 2px */    \n"
"    border-radius: 5px;  /* Скругленные углы */\n"
"   text-align: left;\n"
"    padding-left: 25px; /* Отступ слева для текста */\n"
"    font-size: 16px;  /* Размер шрифта */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #3B3F45;  /* Более светлый фон при наведении */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgba(255, 255, 255, 0.1);  /* 10% белый фон при нажатии */\n"
"    border: 2px solid #FFFFFF;  /* Белая рамка при нажатии */\n"
"}")
        self.delete_button_eq.setObjectName("delete_button_eq")
        self.add_button_eq = QtWidgets.QPushButton(self.equip)
        self.add_button_eq.setGeometry(QtCore.QRect(190, 30, 131, 23))
        self.add_button_eq.setStyleSheet("QPushButton {\n"
"    background-color: #171F34;  /* Темный фон для кнопок */\n"
"    color: #FFFFFF;  /* Белый текст */\n"
"    border: 2px solid white; /* Белая рамка толщиной 2px */    \n"
"    border-radius: 5px;  /* Скругленные углы */\n"
"   text-align: left;\n"
"    padding-left: 25px; /* Отступ слева для текста */\n"
"    font-size: 16px;  /* Размер шрифта */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #3B3F45;  /* Более светлый фон при наведении */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgba(255, 255, 255, 0.1);  /* 10% белый фон при нажатии */\n"
"    border: 2px solid #FFFFFF;  /* Белая рамка при нажатии */\n"
"}")
        self.add_button_eq.setObjectName("add_button_eq")
        self.change_button_eq = QtWidgets.QPushButton(self.equip)
        self.change_button_eq.setGeometry(QtCore.QRect(490, 30, 131, 23))
        self.change_button_eq.setStyleSheet("QPushButton {\n"
"    background-color: #171F34;  /* Темный фон для кнопок */\n"
"    color: #FFFFFF;  /* Белый текст */\n"
"    border: 2px solid white; /* Белая рамка толщиной 2px */    \n"
"    border-radius: 5px;  /* Скругленные углы */\n"
"   text-align: left;\n"
"    padding-left: 25px; /* Отступ слева для текста */\n"
"    font-size: 16px;  /* Размер шрифта */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #3B3F45;  /* Более светлый фон при наведении */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgba(255, 255, 255, 0.1);  /* 10% белый фон при нажатии */\n"
"    border: 2px solid #FFFFFF;  /* Белая рамка при нажатии */\n"
"}")
        self.change_button_eq.setObjectName("change_button_eq")
        self.add_button_med_3 = QtWidgets.QPushButton(self.equip)
        self.add_button_med_3.setGeometry(QtCore.QRect(40, 30, 131, 23))
        self.add_button_med_3.setStyleSheet("QPushButton {\n"
"    background-color: #171F34;  /* Темный фон для кнопок */\n"
"    color: #FFFFFF;  /* Белый текст */\n"
"    border: 2px solid white; /* Белая рамка толщиной 2px */    \n"
"    border-radius: 5px;  /* Скругленные углы */\n"
"   text-align: left;\n"
"    padding-left: 25px; /* Отступ слева для текста */\n"
"    font-size: 16px;  /* Размер шрифта */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #3B3F45;  /* Более светлый фон при наведении */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgba(255, 255, 255, 0.1);  /* 10% белый фон при нажатии */\n"
"    border: 2px solid #FFFFFF;  /* Белая рамка при нажатии */\n"
"}")
        self.add_button_med_3.setObjectName("add_button_med_3")
        self.tabWidget.addTab(self.equip, "")
        self.pacients = QtWidgets.QWidget()
        self.pacients.setObjectName("pacients")
        self.delete_button_pac = QtWidgets.QPushButton(self.pacients)
        self.delete_button_pac.setGeometry(QtCore.QRect(340, 30, 131, 23))
        self.delete_button_pac.setStyleSheet("QPushButton {\n"
"    background-color: #171F34;  /* Темный фон для кнопок */\n"
"    color: #FFFFFF;  /* Белый текст */\n"
"    border: 2px solid white; /* Белая рамка толщиной 2px */    \n"
"    border-radius: 5px;  /* Скругленные углы */\n"
"   text-align: left;\n"
"    padding-left: 25px; /* Отступ слева для текста */\n"
"    font-size: 16px;  /* Размер шрифта */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #3B3F45;  /* Более светлый фон при наведении */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgba(255, 255, 255, 0.1);  /* 10% белый фон при нажатии */\n"
"    border: 2px solid #FFFFFF;  /* Белая рамка при нажатии */\n"
"}")
        self.delete_button_pac.setObjectName("delete_button_pac")
        self.add_button_pac = QtWidgets.QPushButton(self.pacients)
        self.add_button_pac.setGeometry(QtCore.QRect(190, 30, 131, 23))
        self.add_button_pac.setStyleSheet("QPushButton {\n"
"    background-color: #171F34;  /* Темный фон для кнопок */\n"
"    color: #FFFFFF;  /* Белый текст */\n"
"    border: 2px solid white; /* Белая рамка толщиной 2px */    \n"
"    border-radius: 5px;  /* Скругленные углы */\n"
"   text-align: left;\n"
"    padding-left: 25px; /* Отступ слева для текста */\n"
"    font-size: 16px;  /* Размер шрифта */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #3B3F45;  /* Более светлый фон при наведении */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgba(255, 255, 255, 0.1);  /* 10% белый фон при нажатии */\n"
"    border: 2px solid #FFFFFF;  /* Белая рамка при нажатии */\n"
"}")
        self.add_button_pac.setObjectName("add_button_pac")
        self.change_button_pac = QtWidgets.QPushButton(self.pacients)
        self.change_button_pac.setGeometry(QtCore.QRect(490, 30, 131, 23))
        self.change_button_pac.setStyleSheet("QPushButton {\n"
"    background-color: #171F34;  /* Темный фон для кнопок */\n"
"    color: #FFFFFF;  /* Белый текст */\n"
"    border: 2px solid white; /* Белая рамка толщиной 2px */    \n"
"    border-radius: 5px;  /* Скругленные углы */\n"
"   text-align: left;\n"
"    padding-left: 25px; /* Отступ слева для текста */\n"
"    font-size: 16px;  /* Размер шрифта */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #3B3F45;  /* Более светлый фон при наведении */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgba(255, 255, 255, 0.1);  /* 10% белый фон при нажатии */\n"
"    border: 2px solid #FFFFFF;  /* Белая рамка при нажатии */\n"
"}")
        self.change_button_pac.setObjectName("change_button_pac")
        self.add_button_med_4 = QtWidgets.QPushButton(self.pacients)
        self.add_button_med_4.setGeometry(QtCore.QRect(40, 30, 131, 23))
        self.add_button_med_4.setStyleSheet("QPushButton {\n"
"    background-color: #171F34;  /* Темный фон для кнопок */\n"
"    color: #FFFFFF;  /* Белый текст */\n"
"    border: 2px solid white; /* Белая рамка толщиной 2px */    \n"
"    border-radius: 5px;  /* Скругленные углы */\n"
"   text-align: left;\n"
"    padding-left: 25px; /* Отступ слева для текста */\n"
"    font-size: 16px;  /* Размер шрифта */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #3B3F45;  /* Более светлый фон при наведении */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgba(255, 255, 255, 0.1);  /* 10% белый фон при нажатии */\n"
"    border: 2px solid #FFFFFF;  /* Белая рамка при нажатии */\n"
"}")
        self.add_button_med_4.setObjectName("add_button_med_4")
        self.tabWidget.addTab(self.pacients, "")
        self.emp = QtWidgets.QWidget()
        self.emp.setObjectName("emp")
        self.delete_button_emp = QtWidgets.QPushButton(self.emp)
        self.delete_button_emp.setGeometry(QtCore.QRect(340, 30, 131, 23))
        self.delete_button_emp.setStyleSheet("QPushButton {\n"
"    background-color: #171F34;  /* Темный фон для кнопок */\n"
"    color: #FFFFFF;  /* Белый текст */\n"
"    border: 2px solid white; /* Белая рамка толщиной 2px */    \n"
"    border-radius: 5px;  /* Скругленные углы */\n"
"   text-align: left;\n"
"    padding-left: 25px; /* Отступ слева для текста */\n"
"    font-size: 16px;  /* Размер шрифта */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #3B3F45;  /* Более светлый фон при наведении */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgba(255, 255, 255, 0.1);  /* 10% белый фон при нажатии */\n"
"    border: 2px solid #FFFFFF;  /* Белая рамка при нажатии */\n"
"}")
        self.delete_button_emp.setObjectName("delete_button_emp")
        self.add_button_emp = QtWidgets.QPushButton(self.emp)
        self.add_button_emp.setGeometry(QtCore.QRect(190, 30, 131, 23))
        self.add_button_emp.setStyleSheet("QPushButton {\n"
"    background-color: #171F34;  /* Темный фон для кнопок */\n"
"    color: #FFFFFF;  /* Белый текст */\n"
"    border: 2px solid white; /* Белая рамка толщиной 2px */    \n"
"    border-radius: 5px;  /* Скругленные углы */\n"
"   text-align: left;\n"
"    padding-left: 25px; /* Отступ слева для текста */\n"
"    font-size: 16px;  /* Размер шрифта */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #3B3F45;  /* Более светлый фон при наведении */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgba(255, 255, 255, 0.1);  /* 10% белый фон при нажатии */\n"
"    border: 2px solid #FFFFFF;  /* Белая рамка при нажатии */\n"
"}")
        self.add_button_emp.setObjectName("add_button_emp")
        self.change_button_emp = QtWidgets.QPushButton(self.emp)
        self.change_button_emp.setGeometry(QtCore.QRect(490, 30, 131, 23))
        self.change_button_emp.setStyleSheet("QPushButton {\n"
"    background-color: #171F34;  /* Темный фон для кнопок */\n"
"    color: #FFFFFF;  /* Белый текст */\n"
"    border: 2px solid white; /* Белая рамка толщиной 2px */    \n"
"    border-radius: 5px;  /* Скругленные углы */\n"
"   text-align: left;\n"
"    padding-left: 25px; /* Отступ слева для текста */\n"
"    font-size: 16px;  /* Размер шрифта */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #3B3F45;  /* Более светлый фон при наведении */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgba(255, 255, 255, 0.1);  /* 10% белый фон при нажатии */\n"
"    border: 2px solid #FFFFFF;  /* Белая рамка при нажатии */\n"
"}")
        self.change_button_emp.setObjectName("change_button_emp")
        self.add_button_med_5 = QtWidgets.QPushButton(self.emp)
        self.add_button_med_5.setGeometry(QtCore.QRect(40, 30, 131, 23))
        self.add_button_med_5.setStyleSheet("QPushButton {\n"
"    background-color: #171F34;  /* Темный фон для кнопок */\n"
"    color: #FFFFFF;  /* Белый текст */\n"
"    border: 2px solid white; /* Белая рамка толщиной 2px */    \n"
"    border-radius: 5px;  /* Скругленные углы */\n"
"   text-align: left;\n"
"    padding-left: 25px; /* Отступ слева для текста */\n"
"    font-size: 16px;  /* Размер шрифта */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #3B3F45;  /* Более светлый фон при наведении */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgba(255, 255, 255, 0.1);  /* 10% белый фон при нажатии */\n"
"    border: 2px solid #FFFFFF;  /* Белая рамка при нажатии */\n"
"}")
        self.add_button_med_5.setObjectName("add_button_med_5")
        self.tabWidget.addTab(self.emp, "")
        self.stackedWidget.addWidget(self.DirectoryPage)
        self.SettingsPage = QtWidgets.QWidget()
        self.SettingsPage.setObjectName("SettingsPage")
        self.label_8 = QtWidgets.QLabel(self.SettingsPage)
        self.label_8.setGeometry(QtCore.QRect(490, 250, 391, 41))
        self.label_8.setStyleSheet(" color: #FFFFFF;  /* Белый текст */\n"
"    border: none;  /* Убрать рамки */\n"
"    font-size: 40px;  /* Размер шрифта */")
        self.label_8.setObjectName("label_8")
        self.stackedWidget.addWidget(self.SettingsPage)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(6)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.main_button.setText(_translate("MainWindow", "   Главная"))
        self.equipment_button.setText(_translate("MainWindow", "   Оборудование"))
        self.pacient_button.setText(_translate("MainWindow", "   Пациенты"))
        self.documents_button.setText(_translate("MainWindow", "   Документы"))
        self.chat_button.setText(_translate("MainWindow", "   Сообщения"))
        self.settings_button.setText(_translate("MainWindow", "   Настройки"))
        self.exit_button.setText(_translate("MainWindow", "Выйти"))
        self.directory_button.setText(_translate("MainWindow", "   Справочники"))
        self.label_9.setText(_translate("MainWindow", "Добро пожаловать!"))
        self.label.setText(_translate("MainWindow", "Пациенты"))
        self.pushButton.setText(_translate("MainWindow", "Просмотр"))
        self.label_2.setText(_translate("MainWindow", "Развернутый анализ"))
        self.label_3.setText(_translate("MainWindow", "Текущие обследования"))
        self.label_4.setText(_translate("MainWindow", "Тут будет оборудование"))
        self.label_5.setText(_translate("MainWindow", "Тут будут пациенты"))
        self.label_6.setText(_translate("MainWindow", "Тут будут документы"))
        self.label_7.setText(_translate("MainWindow", "Тут будут сообщения"))
        self.tabWidget.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.add_button_med.setText(_translate("MainWindow", "Добавить"))
        self.delete_button_med.setText(_translate("MainWindow", "  Удалить"))
        self.change_button_med.setText(_translate("MainWindow", "Изменить"))
        self.check_button_med.setText(_translate("MainWindow", "Просмотр"))
        self.label_11.setText(_translate("MainWindow", "Название учреждения    :"))
        self.label_12.setText(_translate("MainWindow", "Адрес                            :"))
        self.label_13.setText(_translate("MainWindow", "Телефон                        :"))
        self.label_14.setText(_translate("MainWindow", "Email                             :"))
        self.label_15.setText(_translate("MainWindow", "Тип учреждения            :"))
        self.label_16.setText(_translate("MainWindow", "Сайт                              :"))
        self.label_17.setText(_translate("MainWindow", "Часы работы                  :"))
        self.label_18.setText(_translate("MainWindow", "Главный врач                :"))
        self.send_button_med.setText(_translate("MainWindow", "Отправить"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.med_inst), _translate("MainWindow", "Медицинские учреждения"))
        self.delete_button_eq.setText(_translate("MainWindow", "  Удалить"))
        self.add_button_eq.setText(_translate("MainWindow", "Добавить"))
        self.change_button_eq.setText(_translate("MainWindow", "Изменить"))
        self.add_button_med_3.setText(_translate("MainWindow", "Просмотр"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.equip), _translate("MainWindow", "Оборудование"))
        self.delete_button_pac.setText(_translate("MainWindow", "  Удалить"))
        self.add_button_pac.setText(_translate("MainWindow", "Добавить"))
        self.change_button_pac.setText(_translate("MainWindow", "Изменить"))
        self.add_button_med_4.setText(_translate("MainWindow", "Просмотр"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.pacients), _translate("MainWindow", "Пациенты"))
        self.delete_button_emp.setText(_translate("MainWindow", "  Удалить"))
        self.add_button_emp.setText(_translate("MainWindow", "Добавить"))
        self.change_button_emp.setText(_translate("MainWindow", "Изменить"))
        self.add_button_med_5.setText(_translate("MainWindow", "Просмотр"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.emp), _translate("MainWindow", "Сотрудники"))
        self.label_8.setText(_translate("MainWindow", "Тут будут настройки"))

